depromeet/SPOT-server

README.md
application/build.gradle.kts
application/src/main/java/org/depromeet/spot/application/Main.java
application/src/main/java/org/depromeet/spot/application/SpotApplication.java
application/src/main/java/org/depromeet/spot/application/config/SpotApplicationConfig.java
application/src/main/java/org/depromeet/spot/application/sample/controller/SampleController.java
application/src/main/java/org/depromeet/spot/application/sample/controller/request/SampleRequest.java
application/src/main/java/org/depromeet/spot/application/sample/controller/response/SampleResponse.java
application/src/main/resources/application.yaml
build.gradle.kts
domain/build.gradle.kts
domain/src/main/java/org/depromeet/spot/Main.java

- 서버 어플리케이션을 생성하고 기본적인 설정들을 추가해요.
<br>
<br>
- swagger 실행 화면
- /swagger-ui로 접근하면 보여용

[BSVR-42] 프로젝트 생성 및 멀티 모듈 추가

---

application/src/main/java/org/depromeet/spot/application/member/dto/response/MemberResponse.java
domain/src/main/java/org/depromeet/spot/domain/block/Block.java
domain/src/main/java/org/depromeet/spot/domain/block/BlockRow.java
domain/src/main/java/org/depromeet/spot/domain/block/BlockTopKeyword.java
domain/src/main/java/org/depromeet/spot/domain/member/Member.java
domain/src/main/java/org/depromeet/spot/domain/review/Keyword.java
domain/src/main/java/org/depromeet/spot/domain/review/Review.java
domain/src/main/java/org/depromeet/spot/domain/review/ReviewImage.java
domain/src/main/java/org/depromeet/spot/domain/review/ReviewKeyword.java
domain/src/main/java/org/depromeet/spot/domain/seat/Seat.java
domain/src/main/java/org/depromeet/spot/domain/section/Section.java
domain/src/main/java/org/depromeet/spot/domain/stadium/Stadium.java
domain/src/main/java/org/depromeet/spot/domain/team/BaseballTeam.java
domain/src/main/java/org/depromeet/spot/domain/team/StadiumHomeTeam.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockEntity.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockRowEntity.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockTopKeywordEntity.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/KeywordEntity.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewEntity.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewImageEntity.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewKeywordEntity.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/entity/SeatEntity.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/entity/SectionEntity.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/stadium/entity/StadiumEntity.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/entity/BaseballTeamEntity.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/entity/StadiumHomeTeamEntity.java
usecase/src/main/java/org/depromeet/spot/usecase/service/MemberService.java

- [ERD](https://www.notion.so/depromeet/ERD-bcaa9f32610c4563b902cbb714f956d0?pvs=4#37542fb04ab646809579949491ea1aed)를 바탕으로 도메인과 엔티티를 세팅해요
<br>
- Block쪽 도메인 & 엔티티 세팅
- Member쪽 도메인 & 엔티티 세팅
- Review쪽 도메인 & 엔티티 세팅
- Seat쪽 도메인 & 엔티티 세팅
- Section쪽 도메인 & 엔티티 세팅
- Stadium쪽 도메인 & 엔티티 세팅
- Team쪽 도메인 & 엔티티 세팅
<br>
- 일단 우리가 3명이라 stadium, review, member로 분리해서 ERD를 설계했는데 패키지를 이렇게 꼭 나눌 필요는 없다고 생각했어!
- 그래서 api를 생각해서 패키지를 아래와 같이 분리를 했는데 의견있다면 수정해서 반영할게. 
- 리뷰쪽은 keyword랑 image쪽을 분리를 시킬까 고민 중인데 따로따로 쓰이지는 않을 것 같아서 일단 합쳐놓았어..!
<br>
- @EunjiShin [Stadium ERD](https://dbdiagram.io/d/SPOTstadium-668ce5cb9939893dae6a483f) 참고!
- @pminsung12 [Review ERD](https://dbdiagram.io/d/SPOTreview-668cf8849939893dae6cdb2c) 참고!
- @wjdwnsdnjs13 [Member ERD](https://dbdiagram.io/d/SPOTmember-668daeb99939893dae7d6f6c) 참고!
<br> …

[BSVR-81] Domain과 Entity 기본 세팅

---

application/src/main/java/org/depromeet/spot/application/block/BlockReadController.java
common/src/main/java/org/depromeet/spot/common/exception/block/BlockErrorCode.java
common/src/main/java/org/depromeet/spot/common/exception/block/BlockException.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockRepositoryImpl.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockRowJpaRepository.java
usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/BlockReadUsecase.java
usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockRepository.java
usecase/src/main/java/org/depromeet/spot/usecase/service/block/BlockReadService.java
usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeBlockRepository.java

-  클라이언트 요청으로 특정 블록의 열 정보 조회 API를 만들었어요.
<br>
- 개요와 동일
<br>
- 성공
- 존재하지 않는 블럭

[BSVR-129] 블록의 열별 좌석 범위 조회 API

---

.github/workflows/dev-build-and-deploy.yaml
infrastructure/jpa/src/main/resources/application-jpa.yaml

- 새로운 개발환경 세팅 후 github release가 커밋마다 찍히는 이슈를 해결하고 로컬에서는 도커가 아닌 로컬 DB를 사용하도록 설정을 수정했어요
- resolve #45 
<br>
- 재배포
- github release 버전관리
<br>
<br>

[BSVR-134] github release 관련한 github action 스크립트 파일 수정 및 배포 테스트

---

infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/objectstorage/ImageUploader.java

- 클라이언트 요청으로, 경기장 좌석 배치도 미리보기 파일의 확장자를 svg -> png로 변경했어요
<br>
- 경기장 좌석배치도 타입의 미디어 확장자 검증 로직 수정

[NO_JIRA] 좌석배치도 미리보기 파일 확장자 변경

---

.github/workflows/dev-build-and-deploy.yaml

- ncp object storage 환경변수 추가
<br>
- github action 스크립트에서 deploy 쪽에 docker 실행 시 object storage accessKey, secretKey 환경변수 직접 주입
- github action secret 추가
<br>
- 잘 된다!

[BSVR-138] ncp object storage 환경변수 추가

---

application/src/main/java/org/depromeet/spot/application/block/dto/response/RowInfoResponse.java
domain/src/main/java/org/depromeet/spot/domain/block/Block.java
domain/src/main/java/org/depromeet/spot/domain/block/BlockRow.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/repository/SeatJpaRepository.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/repository/SeatRepositoryImpl.java
usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/BlockReadUsecase.java
usecase/src/main/java/org/depromeet/spot/usecase/port/in/seat/ReadSeatUsecase.java
usecase/src/main/java/org/depromeet/spot/usecase/service/block/BlockReadService.java
usecase/src/main/java/org/depromeet/spot/usecase/service/seat/ReadSeatService.java
usecase/src/test/java/org/depromeet/spot/usecase/service/block/BlockReadServiceTest.java
usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSeatRepository.java

- resolve #60 
<br>
- 구역내 블럭 열별 좌석 범위 조회 API 수정
- 특정 블럭 열별 좌석 범위 조회 API 수정
<br>

[BSVR-143] 블럭 열별 좌석 범위 조회 API res 수정

---

.github/workflows/dev-build-and-deploy.yaml

- DB 스키마 복구를 위해 dev-build-and-deploy.yaml ddl-auto 옵션 update로 변경
<br>
<br>

[BSVR-149] DB 스키마 복구를 위해 dev-build-and-deploy.yaml ddl-auto 옵션 update로 변경

---

.github/workflows/dev-build-and-deploy.yaml

[BSVR-151] ddl-auto update 옵션으로 deploy

---

.github/workflows/dev-build-and-deploy.yaml

- github action 스크립트 파일에서 ddl_auto 환경변수를 create로 설정했던 부분을 다시 validate로 바꿔줬어요!
<br>

[CI/CD] dev-build-and-deploy.yaml ddl-auto 옵션 validate로 변경

---

application/src/main/java/org/depromeet/spot/application/member/dto/response/MyHomeResponse.java
application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java
application/src/main/java/org/depromeet/spot/application/review/dto/response/MyRecentReviewResponse.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewJpaRepository.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewRepositoryImpl.java
infrastructure/jpa/src/main/resources/data.sql
usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java
usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java

- 홈 피드 화면 API
- teamId 리턴 포함
- 최근 리뷰 API
- 총 리뷰수
- data.sql 수정
<br>
- 최근 리뷰 API
- 총 리뷰 수
- 가장 최근 작성한 리뷰
- 나의 정보 API 수정
- teamId 리턴 포함 
- data.sql
- my_team 컬럼 삭제
<br>

[BSVR-160] 홈 피드 화면 리뷰 도메인 API 추가

---

infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewJpaRepository.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewRepositoryImpl.java
usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java

- Review Repository 쪽 충돌해결
<br>
- 충돌 해결하면서 메서드가 중복으로 정의되어 있는 이슈 해결
<br>
- 잘 실행된다.

[BSVR-163] 160 && 162 브랜치 Review Repository 쪽 충돌해결

---

.github/workflows/dev-build-and-deploy.yaml

[BUG] 프로필 prod->dev

---

domain/src/main/java/org/depromeet/spot/domain/member/Member.java

- 후기 개수에 따라 레벨을 계산하는 정책을 변경해요
<br>
- 개요와 동일

[BSVR-183] 레벨 계산 로직 변경

---

application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
application/src/main/java/org/depromeet/spot/application/member/controller/LevelUpTableController.java
application/src/main/java/org/depromeet/spot/application/member/dto/response/LevelUpTableResponse.java
domain/build.gradle.kts
domain/src/main/java/org/depromeet/spot/domain/member/Level.java
infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/LevelRepositoryImpl.java
usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/LevelUsecase.java
usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/LevelRepository.java
usecase/src/main/java/org/depromeet/spot/usecase/service/level/LevelService.java

- 레벨업 테이블 조회 API
<br>
- getLevelUpTable API 추가
<br>

[BSVR-180] 레벨업 테이블 조회 API

---

domain/build.gradle.kts
domain/src/main/java/org/depromeet/spot/domain/member/Level.java

- ImmutableMap 수정
<br>
- 사용하지 않는 구아바 의존성 제거
- ImmutableMap -> Map.of 사용
- 레벨 계산 알고리즘 수정
<br>
- 관련 작업 : #101
<br>
- 홈 피드(레벨업까지 남은 리뷰 수 확인)
- 레벨업 조건표 API

[NO_JIRA] immutable map fix

---

application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java

- baseball-teams 조회 API jwt filter 제외 추가
<br>
- baseball-teams 조회 API jwt filter 제외 추가
<br>
- 토큰 없이 정상 동작 확인 완료

[NO-JIRA] baseball-teams 조회 API jwt filter 제외 추가

---

application/src/main/resources/banner.txt

- 삭막한 해커톤 중 너희에게 웃음을 주고자......
<br>
- banner.txt 추가
<br>
어플리케이션을 실행하면 요런 콘솔 로그가 뜹니다 ^___^ 👍

[NO_JIRA] banner.txt 추가

---

application/src/main/resources/logback-spring.xml

- 아직 loki 세팅 전이라 불필요한 에러 계속 발생..! appender 잠시 꺼둘게요
<br>
- 개요와 동일
<br>
- #116 작업 완료될 때 appender 다시 추가 필요

[NO_JIRA] loki 설정 전까지 prod에 Loki Appender 비활성화

---

application/src/main/resources/logback-spring.xml
infrastructure/src/main/java/org/depromeet/spot/infrastructure/aws/objectstorage/PresignedUrlGenerator.java

- #118 디버깅을 위해 로그 추가 및 임시 prod 로그 레벨 조정
- dev 서버가 아직 없고, prod는 심사 Ing라 유저가 없기 때문에.. 임시로 여기서 디버깅 진행해요
<br>
- 로그 추가

[NO_JIRA] 디버깅을 위한 presigned url log 추가

---

.github/workflows/dev-build-and-deploy.yaml
.github/workflows/manual-prod-deploy.yaml
.gitignore
Dockerfile
application/src/main/resources/appenders/console-appender.xml
application/src/main/resources/application.yaml
infrastructure/src/main/java/org/depromeet/spot/infrastructure/aws/config/ObjectStorageConfig.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/aws/objectstorage/ImageUploader.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/aws/objectstorage/PresignedUrlGenerator.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/aws/property/ObjectStorageProperties.java
infrastructure/src/main/resources/application-ncp.yaml
infrastructure/src/test/java/org/depromeet/spot/infrastructure/aws/PresignedUrlGeneratorTest.java

- NCP에 있던 개발서버를 AWS로 마이그레이션 하면서 object storage 연결하는 부분을 수정했어요.
<br>
- application-aws.yaml을 이제 gitignore로 관리해요. 컨플로언스에 파일 내용 올려놓았어요.
<br>

[BSVR-190] 개발 서버 AWS 마이그레이션

---

application/src/main/java/org/depromeet/spot/application/common/config/SecurityConfig.java
application/src/main/java/org/depromeet/spot/application/common/exception/CustomJwtException.java
application/src/main/java/org/depromeet/spot/application/common/exception/ErrorResponse.java
application/src/main/java/org/depromeet/spot/application/common/exception/ExceptionHandlerFilter.java
application/src/main/java/org/depromeet/spot/application/common/exception/JwtErrorCode.java
application/src/main/java/org/depromeet/spot/application/common/exception/SpotAppExceptionHandler.java
application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
application/src/main/java/org/depromeet/spot/application/common/jwt/JwtTokenUtil.java
application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java
common/src/main/java/org/depromeet/spot/common/exception/oauth/OauthErrorCode.java
common/src/main/java/org/depromeet/spot/common/exception/oauth/OauthException.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/OauthRepositoryImpl.java

- JWT 필터 로직 수정
- Filter Exception handling
- Oauth Exception
<br>
- JWT 필터
- 요청 메소드 별 화이트리스트 구현
- Filter Exception handling
- Oauth Exception 추가
- Exception Handler
- CustomJwtException 추가
- MethodArgumentNotValidException 추가
<br>
- 미안해... 작업하다 보니까 연결된 곳에서 문제가 여럿 터져서 작업이 분할이 안되고 섞였어...ㅠㅠ
<br>
- #34
<br>
- JWT 필수 요청 URL
- (Oauth) 올바르지 않은 액세스 토큰
- (Oauth) 존재하지 않는 유저 로그인 요청
- MethodArgumentNotValidException

[BSVR-189] JWT 필터 로직 수정, Filter Exception handling, Oauth exception

---

.gitignore
application/.gitignore
application/src/main/resources/appenders/console-appender.xml
application/src/main/resources/application.yaml
application/src/main/resources/logback-spring.xml

- Loki 모니터링 인스턴스 ip 설정
<br>
- Loki 모니터링 인스턴스 ip 설정
- 모니터링 인스턴스 IP 환경변수로 수정
- loki appender 부분 logback 파일로 이동
- property 태그가 configuration 태그와 함께 있어야하는 것으로 파악하였음.
- **컨플루언스 확인해서 yml 파일 추가가 필요해요!**
<br>

[NO_JIRA] Loki 모니터링 인스턴스 ip 설정

---

application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
application/src/main/java/org/depromeet/spot/application/common/jwt/JwtTokenUtil.java
application/src/main/java/org/depromeet/spot/application/member/controller/JwtCreateController.java

- jwt 이슈 해결
<br>
- jwt 이슈 해결
- 파라미터명을 token으로 해놔서 그거때문에 accessToken이랑 jwt 토큰이랑 혼동해서 코드 짜서 생긴 문제였음...ㅎㅎ
- 원하는 id에 해당하는 jwt 토큰 생성 기능 구현
- id만 입력하면 해당하는 jwt 토큰 생성
<br>
- 테스트하면서 jwt 관련 내용이 좀 있는 거 같아서 원하는 id에 해당하는 jwt를 생성하는 기능을 만들었어. 혹시 필요 없을 거 같으면 리뷰 남겨주면 지울게!
<br>
- #123 
<br>
- JWT 정상 동작 확인!
- 개발용 JWT 생성 동작 확인

[NO-JIRA] jwt fix

---

.github/workflows/dev-build-and-deploy.yaml
.github/workflows/manual-prod-deploy.yaml
application/src/main/resources/logback-spring.xml

[BSVR-202/배포] monitoring yml 트러블 쇼팅

---

.github/workflows/dev-build-and-deploy.yaml
.github/workflows/manual-prod-deploy.yaml
application/src/main/resources/logback-spring.xml

- 프로메테우스 scrape 안되는 이슈 트러블슈팅
<br>

[BSVR-202] 프로메테우스 scrape 안되는 이슈 트러블슈팅

---

.github/workflows/dev-build-and-deploy.yaml
.github/workflows/manual-prod-deploy.yaml

- docker내의 3100번과 서버의 3100번을 매핑해줬어요.

[BSVR-210] 개발 서버 로키 connection 에러 트러블 슈팅

---

.github/workflows/dev-build-and-deploy.yaml

- https://depromeet-15th.slack.com/archives/C075Z9K5QH4/p1723702682695089
- ⬆️ 에서 논의한 개발 서버 자동 태그 생성 기능 삭제
<br>
- github actions 스크립트에서 create-release 부분을 주석처리했어요. 이제 release tag를 남길려면 수동으로 만들어야 해요.
<br>

[BSVR-214] 개발 서버 자동 태그 생성 기능 삭제

---

infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapCustomRepository.java
usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/PaginationProcessor.java
usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/PaginationProcessorImpl.java
usecase/src/main/java/org/depromeet/spot/usecase/service/review/scrap/ReviewScrapService.java
usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewScrapServiceTest.java

- 스크랩 조회 페이지네이션 커서 버그 픽스
<br>
- [페이지네이션 getCursor 메서드 processor로 분리](https://github.com/depromeet/SPOT-server/commit/8fa1db5eadf3087df45849f9fbeebf634db6b8e0)
- [getCursorCondition 조건 위치 버그 픽스](https://github.com/depromeet/SPOT-server/commit/95ce87e1252f89d2691d79d7d3d72506d6e49910)
- [ReviewScrapServiceTest processor 의존성 추가](https://github.com/depromeet/SPOT-server/commit/9d21b4f28136c23f6f4de671b22fd59efaa42c0f)
<br>
- x
<br>
- x
<br>

[BSVR-244] 스크랩 조회 페이지네이션 커서 버그 픽스

---

.github/workflows/dev-build-and-deploy.yaml
.github/workflows/manual-prod-deploy.yaml

- Oauth 환경 변수 추가
<br>
- application-oauth.yaml 파일에 추가한 oauth 환경 변수 추가
<br>

[NO-JIRA] oauth 환경 변수 추가

---

application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/aws/property/ObjectStorageProperties.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/OauthRepositoryImpl.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/entity/GoogleUserInfoEntity.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/entity/KakaoUserInfoEntity.java
infrastructure/src/test/java/org/depromeet/spot/infrastructure/aws/PresignedUrlGeneratorTest.java

- 기본 프로필 이미지 오류 FIX
<br>
- 기본 프로필 null 오류 fix
<br>
- 회원가입
- 정상 값 입력

[NO_JIRA] login fix

---

application/src/main/resources/appenders/console-appender.xml

- 로키 로그에 Spring Profile 추가
<br>
- 로키 로그에 Spring Profile 추가
- 다른 복잡한 방법 쓰는 것보다 그냥 profile로 구분되고 있으니까 해당 변수 사용하도록 변경했어!
<br>
- 로키에서 정상적으로 profile 변수가 잡히는 것 확인!

[BSVR-261] 로키 로그에 Spring Profile 추가

---

domain/src/main/java/org/depromeet/spot/domain/media/extension/ImageExtension.java

- heic 확장자의 리뷰 이미지를 올릴 수 있도록 처리해요
- [관련 스레드](https://depromeet-15th.slack.com/archives/C076JJKKR4H/p1725891085977319)
<br>
- 이미지 확장자 허용 목록에 heic 추가

[NO_JIRA] heic 이미지 확장자 추가

---

.github/workflows/dev-build-and-deploy.yaml
.github/workflows/manual-prod-deploy.yaml

- #192 
<br>
- [actions 스크립트에 LOKI_URL 주입](https://github.com/depromeet/SPOT-server/commit/6896f8ef5bfc9b83e8c9fa96247db5409c36aa69)
<br>
<br>
<br>

[BSVR-262] Secret Manger Loggin Appender 관련 버그 픽스

---

application/src/main/resources/appenders/console-appender.xml

- Loki profile fix
<br>
- Loki profile fix
<br>

[NO_JIRA] Loki profile fix

---

Dockerfile

[NO-JIRA] 메모리 업

---

Dockerfile

[NO_JIRA] 메모리 업

---

infrastructure/src/main/resources/application-jpa.yaml

- 커넥션 풀 최대 300으로 설정
<br>
- 커넥션 풀 최대 300으로 설정
<br>

[NO_JIRA] 커넥션 풀 최대 300으로 설정

---

application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java
application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java
application/src/main/java/org/depromeet/spot/application/review/like/ReviewLikeController.java
application/src/main/java/org/depromeet/spot/application/review/scrap/ReviewScrapController.java
infrastructure/src/main/resources/application-jpa.yaml

[NO-JIRA] mixpanel remove

---

Dockerfile

- Memory resize
- Prod 인스턴스 다운그레이드
- Dev 인스턴스, DB 비활성화(AWS)
<br>
- 초기 힙 크기, 최대 힙 크기 768MB로 수정
- Prod 인스턴스 T2.small -> T2.micro 다운그레이드
- Dev 인스턴스와 DB 비활성화
<br>

[NO_JIRA] memory resize(1024 -> 768 && T2.small -> T2.micro)

---

application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java
common/src/main/java/org/depromeet/spot/common/exception/member/MemberErrorCode.java
common/src/main/java/org/depromeet/spot/common/exception/member/MemberException.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/repository/MemberJpaRepository.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/repository/MemberRepositoryImpl.java
usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java
usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/MemberRepository.java
usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java

- 멤버 수 확인 API
<br>
- membersCount API 추가
- jwtFilter 화이트 리스트 추가
- 멤버가 없을 경우 customException 추가
<br>
- 윤선이의 멤버수를 확인하고 싶다는 요청사항
ㅋㅋㅋㅋ 요청 사항 해결~~^^
<br>
- 로컬 확인

[NO_JIRA] 멤버 수 확인 API 추가

---

application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java

- [NO_JIRA] 멤버 수 API 폰트 스타일 변경
<br>
- [NO_JIRA] 멤버 수 API 폰트 스타일 변경
<br>
- 못 생겨서 ***이쁘게*** 변경함^^

[NO_JIRA] 멤버 수 API 폰트 스타일 변경

---

.github/workflows/dev-build-and-deploy.yaml

- 개발 서버 재배포를 위한 PR
<br>
- action 파일 엔터 추가
<br>

[No-JIRA] 개발 서버 재배포

---

.github/workflows/dev-build-and-deploy.yaml
infrastructure/src/main/java/org/depromeet/spot/infrastructure/common/aop/DistributedLockAop.java

[NO-JIRA] 개발 서버 재배포 2nd

---

.github/workflows/dev-build-and-deploy.yaml
application/src/test/java/org/depromeet/spot/application/ReviewLikeServiceTest.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/common/aop/DistributedLockAop.java

[NO-JIRA] 개발 서버 재배포 3rd

---

.github/workflows/dev-build-and-deploy.yaml
application/src/test/java/org/depromeet/spot/application/ReviewLikeServiceTest.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/common/aop/DistributedLockAop.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/EmbeddedRedisConfig.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/RedissonConfig.java

[NO-JIRA] 개발 서버 재배포 4th

---

.github/workflows/dev-build-and-deploy.yaml
application/src/test/java/org/depromeet/spot/application/ReviewLikeServiceTest.java
application/src/test/resources/application-test.yml
infrastructure/src/main/java/org/depromeet/spot/infrastructure/common/aop/DistributedLockAop.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/EmbeddedRedisConfig.java
infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/RedissonConfig.java

[NO-JIRA] dev deploy 5th
