build.gradle.kts
- makeGitHooksExecutable 에러 fix
<br>
- OS에 따른 명령어 분기처리
- Windows : attrib
- 그 외 : chmod
<br>
- Mac에서도 정상 동작하는지 확인해줬으면 해! ㅎㅎ
=> [BSVR-61] 윈도우에서 makeGitHooksExecutable 에러 fix

.github/workflows/dev-ci.yaml, .github/workflows/pr-size-labeler.yaml
- build와 test를 포함하는 dev용 CI github action 스크립트 작성
<br>
- 작업 순서
1. [publish-unit-test-result-action](https://github.com/EnricoMi/publish-unit-test-result-action) : action 안들어가도 테스트 결과 확인 가능
2. [action-junit-report](https://github.com/mikepenz/action-junit-report) : 실패한 테스트를 PR 란에서 바로 확인 가능
3. [Store test results](https://github.com/actions/upload-artifact) 스텝을 추가하여 테스트 결과를 아티팩트로 저장함. 워크플로우 실행 후에도 결과를 다운로드하여 확인할 수 있음
4. Test Report Summary: 간단한 테스트 결과 요약을 GitHub Actions 실행 페이지에 표시함.
<br>
- x
<br>
- 지금은 main 브랜치에 작업중이라 workflow on 트리거에 main 브랜치를 포함시켰는데, 이 작업은 dev용이라 실제 개발 들어가면 삭제할 예정!
- ncp 크레딧 받아서 인프라 세팅하면 자동배포 추가해 dev-cicd로 업그레이드 예정(환경변수 세팅 필요)
=> [BSVR-62] 개발단계 ci github actions 스크립트 추가

build.gradle.kts, infrastructure/jpa/build.gradle.kts, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/common/P6spySqlFormatter.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/config/P6spyConfig.java, infrastructure/jpa/src/main/resources/application-jpa.yaml, versions.properties
- 내가 작성한 코드가 실제 쿼리로 어떻게 변환되는지 확인하기 위해 쿼리 로그를 추가해요.
- jpa.properties.hibernate.show_sql은 가독성이 좋지 않아서, p6spy 라이브러리를 사용했어요.
<br>
- p6spy 의존성 추가
- 쿼리 로그 포맷터 & 설정 파일 추가
<br>
- 공식 가이드
- [p6spy](https://github.com/p6spy/p6spy) 
- [p6spy-spring-boot-starter](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator?tab=readme-ov-file)
p6spy는 datasource에 프록시로 붙어서 동작해요. spring-boot-starter를 이용해 보다 편리하게 사용할 수 있어요. 
<br>
- jpa.properties.hibernate.show_sql 적용 :: 가독성 안좋고 매개변수도 안보임
- jpa.properties.hibernate.format_sql 추가 적용 :: 가독성은 좋아졌으나 여전히 매개변수 안보임
- show_sql, format_sql 다 지우고 p6spy만 적용 :: 가독성도 좋고 stacktrace도 보이고 실행시간도 보이고 매개변수도 보임 ^^👍
=> [BSVR-55] P6spy를 이용한 쿼리 로그 설정

.editorconfig, application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java, build.gradle.kts, infrastructure/jpa/build.gradle.kts, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/config/QueryDslConfig.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberCustomRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/MemberUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/MemberRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/MemberService.java, versions.properties
- 복잡한 쿼리 & 동적 쿼리 컨트롤을 위해 queryDSL 의존성을 추가해요.
<br>
- queryDSL 의존성, 설정파일 추가
- 샘플 코드 추가
- editorconfig 인덴트 사이즈 조정
- spotless에서 javaFormat.aosp를 사용 중이라 editorconfig랑 안맞는 이슈
- 그냥 javaFormat은 인덴트2인데, aosp는 인덴트4
- 티켓 파긴 작은 이슈라서 여기 PR에서 같이 고쳤어용
<br>
- [JPAQueryFactory를 이용해 상속/구현 없이 queryDSL 사용하기](https://jojoldu.tistory.com/372)
<br>
p6spy도 잘 동작하는 것 확인 완료!
=> [BSVR-56] QueryDSL 설정 추가

domain/src/main/java/org/depromeet/spot/domain/review/Review.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockRowEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockTopKeywordEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/common/entity/BaseEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/KeywordEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewImageEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewKeywordEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/entity/SeatEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/entity/SectionEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/stadium/entity/StadiumEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/entity/BaseballTeamEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/entity/StadiumHomeTeamEntity.java
- 변경된 DB 컨벤션에 맞춰 BaseEntity를 생성하고, 엔티티 클래스에 적용했어요.
<br>
- entity들에 BaseEntity 적용 및 충돌 코드 수정
<br>
- 각자 작업 진행 중일 것 같아서 entity만 수정하고 도메인은 그대로 뒀어용
- 도메인 클래스는 담당자가 작업하면서 필요에 따라 변경해주시면 됩니다~!
- 이제 DB 테이블에는 id, created_at, updated_at, deleted_at 전부 저장되니 각 도메인에선 당장 필요한 필드만 추가하면 될 것 같아용
- 지금 당장은 도메인에 추가 안해도, 나중에 필요할때 추가하면 디비에서 꺼내올 수 있으니 문제 없음! ✨
- **created_at, updated_at은 @PrePersist, @PreUpdate를 통해 동작해요. 즉, 어플리케이션을 통해서가 아니라 DB에 sql을 직접 날리는 경우엔 동작하지 않아요 (data.sql로 데이터 삽입하는 경우 등)** 
- 지금은 ddl-auto를 이용해 스키마를 생성하지만, 실제 개발 / 운영 환경에선 직접 ddl 스크립트를 작성해야해요.
- 그때 테이블 각 필드 created_at, updated_at에 디폴트 값을 배정해주어야 합니덩
=> [BSVR-123] DB 컨벤션에 맞춰 BaseEntity 생성

application/src/main/java/org/depromeet/spot/application/block/BlockReadController.java, application/src/main/java/org/depromeet/spot/application/block/dto/response/BlockCodeInfoResponse.java, common/src/main/java/org/depromeet/spot/common/exception/section/SectionErrorCode.java, common/src/main/java/org/depromeet/spot/common/exception/section/SectionException.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockJpaRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockRepositoryImpl.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/repository/SectionJpaRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/repository/SectionRepositoryImpl.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/stadium/repository/StadiumRepositoryImpl.java, infrastructure/jpa/src/main/resources/data.sql, usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/BlockReadUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/SectionReadUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/stadium/StadiumReadUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/section/SectionRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/stadium/StadiumRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/block/BlockReadService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/section/SectionReadService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSectionRepository.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeStadiumRepository.java
- 경기장 구역 내 블럭 리스트 조회 API
<br>
- 특정 구역 내의 블럭 리스트 조회
- 경기장 내 구역 존재 여부 체크 repository
<br>
- 성공
- 실패 : 존재하지 않는 경기장
- 실패 : 경기장 내 구역 아님
=> [BSVR-97] 특정 경기장 구역 내 블럭 리스트 조회

application/src/main/java/org/depromeet/spot/application/media/MediaController.java, application/src/main/java/org/depromeet/spot/application/stadium/CreateStadiumController.java, application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumResponse.java, common/src/main/java/org/depromeet/spot/common/exception/media/MediaErrorCode.java, common/src/main/java/org/depromeet/spot/common/exception/media/MediaException.java, domain/src/main/java/org/depromeet/spot/domain/media/MediaProperty.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/stadium/repository/StadiumRepositoryImpl.java, infrastructure/ncp/build.gradle.kts, infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/config/ObjectStorageConfig.java, infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/objectstorage/ImageUploader.java, infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/objectstorage/PresignedUrlGenerator.java, infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/property/ObjectStorageProperties.java, infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/property/ReviewStorageProperties.java, infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/property/StadiumStorageProperties.java, infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/resources/application.yaml, infrastructure/ncp/src/test/java/org/depromeet/spot/ncp/objectstorage/PresignedUrlGeneratorTest.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/stadium/CreateStadiumUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/media/CreatePresignedUrlPort.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/media/ImageUploadPort.java, usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/CreateStadiumService.java
- (어드민) 경기장 등록 API
- (어드민) 이미지 업로드 컴포넌트
- 유저 API와 다르게, 어드민 API (경기장, 구역, 블럭 생성 etc)는 1차 MVP 기준 클라이언트가 없어요. 
- presigned url을 이용할 수 없는 환경이기에, 서버에서 직접 이미지를 업로드하도록 컴포넌트를 만들어주었어요.
<br>
- 경기장 등록 API
- object storage 이미지 업로드 컴포넌트
<br>
- ㅠㅠ 코드가 산만하네요.. 일정이 빠듯해서 일단 올립니당 차차 추상화 해볼게요!
<br>
- API 성공
- object storage에 파일 업로드 확인
=> [BSVR-91] 경기장 등록 API & 이미지 업로드 컴포넌트

application/src/main/java/org/depromeet/spot/application/common/dto/RgbCodeRequest.java, application/src/main/java/org/depromeet/spot/application/section/CreateSectionController.java, application/src/main/java/org/depromeet/spot/application/section/dto/request/CreateSectionRequest.java, common/src/main/java/org/depromeet/spot/common/exception/section/SectionErrorCode.java, common/src/main/java/org/depromeet/spot/common/exception/section/SectionException.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/repository/SectionJdbcRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/repository/SectionRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/CreateSectionUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/section/SectionRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/section/CreateSectionService.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSectionRepository.java, usecase/src/test/java/org/depromeet/spot/usecase/service/section/CreateSectionServiceTest.java
- (어드민)특정 경기장에 구역 정보들을 등록해요.
<br>
- 경기장 구역 정보 등록 API
- 관련 테스트 코드
<br>
- 성공
- 중복 별칭
- 중복 이름
- 존재하지 않는 경기장
=> [BSVR-99] 경기장 내 구역 정보 생성

application/src/main/java/org/depromeet/spot/application/member/dto/response/MemberResponse.java, domain/src/main/java/org/depromeet/spot/domain/member/Member.java, domain/src/main/java/org/depromeet/spot/domain/member/enums/MemberRole.java, domain/src/main/java/org/depromeet/spot/domain/member/enums/SnsProvider.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java
- KAKAO 개인 정보 정책으로 인한 Entity 변경
<br>
- MemberEntity 변경
- Member 변경
- Enum 추가
- SnsProvider, MemberRole
<br>
=> [BSVR-127] 멤버 Entity 변경

application/src/main/java/org/depromeet/spot/application/review/ReviewReadController.java, application/src/main/java/org/depromeet/spot/application/review/dto/request/BlockReviewRequest.java, application/src/main/java/org/depromeet/spot/application/review/dto/request/MyReviewRequest.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewCustomRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReviewReadUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReviewReadService.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeReviewRepository.java, usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewReadServiceTest.java
- 내 시야기록 조회 API 구현했어요.
<br>
- 필터링 가능한 레포지토리 및 서비스 함수 구현
- request dto와 controller 구현
<br>
- 아래 코멘트에서 확인해주세요.
<br>
- 준원이 PR이 머지되서 이제 유저 정보가 토큰 형태로 들어오면 userId 추출하는 리팩토링 필요!
<br>
- 필터링 없이 전체 조회
- 연도 필터링 조회
- 아이템 없는 경우 -> 200 ok 지만 reviews 배열이 비어있는 형태로 반환
- 테스트 결과
=> [BSVR]-119 내 시야기록 조회 API 구현

application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumInfoWithSeatChartResponse.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/stadium/StadiumReadUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
- 클라이언트 요청으로 특정 경기장 조회 API에 경기장 메인 이미지 res 추가
<br>
- 개요와 동일!
=> [BSVR-130] 경기장 조회 API res에 썸네일 추가

application/src/main/java/org/depromeet/spot/application/block/BlockReadController.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockJpaRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockRepositoryImpl.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockRowJpaRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/BlockReadUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/block/BlockReadService.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeBlockRepository.java
- 클라이언트 요청으로 #41 의 API request를 수정했어요.
- [관련 스레드](https://depromeet-15th.slack.com/archives/C076JJKKR4H/p1721236847708919)
<br>
- controller 변경
- 그에 맞춰 서비스, 레포지토리 구현 변경
- fake test 추가
<br>
- 변경된 spec
- 성공
- 존재하지 않는 경기장
- 존재하지 않는 블럭 코드
=> [NO_JIRA] 블록별 좌석 범위 조회 API request 수정

application/src/main/resources/application.yaml
- presigned url 없이 직접 이미지를 업로드할 때, mutli file size와 request size 조정이 필요해요.
<br>
- max file size 변경
- as-is : 1MB (default)
- to-be : 10MB
- max request size 변경
- as-is :  10MB
- to-be : 30MB
=> [NO_JIRA] 업로드 가능한 최대 파일 사이즈 조정

application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java, usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
- 로그인 시 존재하지 않는 유저 빈 JWT 리턴하도록 변경
<br>
- 카카오 로그인/회원가입 화면 통일.
- 로그인 요청 후 존재하지 않을 경우 빈 JWT 리턴.
- 회원가입 flow로 이동하도록 함
<br>
- 로그인
- 로그인 실패
=> [NO_JIRA_KAKAO_oauth] 로그인 시 존재하지 않는 유저는 빈 JWT 리턴하도록 변경

infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockJpaRepository.java
- 특정 경기장 특정 구역 내에 있는 블럭 리스트를 조회할 때, 블럭 코드 오름차순이 되게 정렬을 추가해요
<br>
- 개요와 동일
<br>
=> [BSVR-142] 구역 내 블록 조회시 블럭 코드 오름차순 정렬

application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberJpaRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/MemberRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
- accessToken을 사용한 멤버 삭제 구현
<br>
- 멤버 삭제 API
- TODO : 회원 탈퇴가 아니므로 추후 개발해야함.
<br>
- 멤버 삭제 성공
- 멤버 삭제 실패
=> [NO_JIRA] accessToken을 사용한 멤버 삭제 API

application/build.gradle.kts, application/src/main/java/org/depromeet/spot/application/common/annotation/CurrentMember.java, application/src/main/java/org/depromeet/spot/application/common/annotation/MemberId.java, application/src/main/java/org/depromeet/spot/application/common/aop/JwtTokenAspect.java, application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java, application/src/main/java/org/depromeet/spot/application/common/jwt/JwtToken.java, application/src/main/java/org/depromeet/spot/application/common/jwt/JwtTokenEnums.java, application/src/main/java/org/depromeet/spot/application/common/jwt/JwtTokenUtil.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/oauth/OauthRepositoryImpl.java
- 헤더 jwt 토큰에서 memberId 가져오는 AOP 추가
- Jwt 토큰 형식 변경
- @MemberId 커스텀 어노테이션 추가
<br>
- 헤더 jwt 토큰에서 memberId 가져오는 AOP 추가
- Jwt 토큰 형식 변경
- memberId String -> Long 타입 변경
- memberId Subject -> claim 으로 변경
- @MemberId 커스텀 어노테이션 추가
- 메서드에 사용되는 커스텀 어노테이션 추가
- 어노테이션 사용법 추가
- 마우스 올리면 나옵니당
<br>
- 제대로 동작하는지 확인해줬으면 해요.
- Request body랑 query Param, path variable는 영향 안 주는지 확인 했는데 혹시 모르니 한 번 체크 부탁드립니당~~~
- Header랑 request 자체를 건들어서 확인해봤어
- Test용으로 GET과 POST 테스트를 했지만 처음 해보는 거라 걱정돼...ㅋㅋㅋ
<br>
- GET 테스트
- POST 테스트
=> [BSVR-78] Jwt 토큰 수정, 헤더 jwt 토큰에서 memberId 가져오는 AOP 추가

application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/repository/SeatJpaRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/repository/SeatRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/CreateReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/seat/SeatRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSeatRepository.java
- 클라이언트에서 seatId를 모르기 때문에, blockId와 seatNumber를 이용해 좌석을 추적하도록 수정해요.
<br>
- seatId를 이용하던 API를 blockId, seatNumber를 이용하도록 수정
<br>
- #71 로 스키마 변경 된 후에 실행 가능해용
<br>
성공
실패 (블럭에 해당 좌석 없음)
=> [BSVR-150] blockId, seatNumber를 이용하도록 리뷰 생성 API 수정

application/src/main/java/org/depromeet/spot/application/review/DeleteReviewController.java, application/src/main/java/org/depromeet/spot/application/review/dto/response/DeleteResponse.java, application/src/main/java/org/depromeet/spot/application/review/dto/response/MyReviewListResponse.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewJpaRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/DeleteReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/DeleteReviewService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
- 리뷰 삭제 API를 구현
<br>
- soft delete 방식을 사용해 리뷰를 삭제하는 API를 구현했어요.
- 엄밀히 말하면 삭제가 아닌 deleted_at 값을 업데이트!
- 삭제는 신중해야하기 때문에 aos는 review pk만 요청으로 보내지만 토큰의 memberId도 가지고 와서 이 두개를 함꼐 사용해 리뷰를 삭제해줬어요.
- 조회할 때 deleted_at이 null인 것만 조회하도록 업데이트를 해야하지만 이미 등록할 때 잘 처리해뒀어요~
<br>
- 잘 삭제 된다!
- 삭제한 리뷰에만 deleted_at 컬럼에 지운 날짜가 들어간 것을 확인!
=> [BSVR-159] 리뷰 삭제 API 구현 (soft delete)

.github/workflows/dev-build-and-deploy.yaml, application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java, application/src/main/java/org/depromeet/spot/application/member/dto/response/MyHomeResponse.java, application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java, common/src/main/java/org/depromeet/spot/common/exception/member/MemberErrorCode.java, common/src/main/java/org/depromeet/spot/common/exception/member/MemberException.java, domain/src/main/java/org/depromeet/spot/domain/member/enums/Level.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberJpaRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberRepositoryImpl.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/repository/SeatJpaRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/repository/SeatRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/CreateReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/MemberRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/seat/SeatRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSeatRepository.java
- 유저 레벨별 칭호를 관리하고, 내 정보 조회 API response에 추가해요.
<br>
- 레벨-칭호 관리 enum 추가
- 내 정보 조회 API res에 칭호 정보 추가
<br>
- [브랜치 한번 꼬여서](https://github.com/depromeet/SPOT-server/pull/78#issuecomment-2246849916), 리뷰 삭제 관련 작업물들까지 포함되었어요! 참고해주세용
- [aos와의 논의 스레드](https://depromeet-15th.slack.com/archives/C076JJKKR4H/p1721790310475679)
- 1차땐 칭호만 있어서 빠른 작업을 위해 enum으로 만들었어요.
- 레벨에 맞는 string만 리턴하면 되는데, DB에 저장하는건 현재 요구사항에 비해 공수가 너무 크다고 판단
- DB 테이블로 분리하면 -> 멤버가 level 테이블을 참조해야하고 (DB 테이블, 엔티티, 도메인 변경 필요), 기존에 작성된 쿼리들도 수정해야 함
- 2차때 레벨별 그래픽이 추가될 예정이니, 그때 테이블로 분리하면 될 것 같아요.
<br>
=> [BSVR-159] level 칭호 기능 추가

application/src/main/java/org/depromeet/spot/application/review/dto/response/MyReviewListResponse.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
- PR 요약
<br>
- 내 리뷰 조회 때 아래 항목을 포함시켜 반환한다.
1. 유저 id
2. 프로필 사진
3. 레벨
4. 닉네임
5. 작성한 총 리뷰 개수
<br>
@EunjiShin @wjdwnsdnjs13 
- 여기 주황색 부분에 레벨 옆에 있는 "전설의 직관러" 이건 닉네임이 아니라 칭호같지 않아?
- 칭호 지정에 대한 부분을 내가 놓쳤나? Member 테이블에는 따로 정의되어 있지 않은 것 같아서
<br>
- memberInfoOnMyReview 부분이 이번 수정때 새롭게 업데이트 된 부분이다!
=> [BSVR-158] 내 리뷰 조회 API 사용자 정보 포함시키도록 업데이트

usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
- 내 리뷰 조회 API response에 칭호 추가
<br>
- usecase result 반환형에 levelTitle 필드를 추가하고 서비스 코드에서 enum에서 받아오는 걸로 했어요
<br>
- 칭호가 잘 들어갔다!
=> [BSVR-161] 내 리뷰 조회 API response에 칭호 추가

.gitignore, application/src/main/java/org/depromeet/spot/application/review/dto/response/BlockReviewListResponse.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewJpaRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
- 블록별 리뷰 조회 Location 정보 최상단으로 응답 구조 변경
<br>
**문제점**
- 리뷰가 비어있으면 아래 화면의 정보를 받지 못한다.
**해결**
- 별도의 쿼리로 stadiumId와 blockCode를 활용해 location 정보를 따로 받아온다.
<br>
- location으로 잘 들어갔다! 이제 review가 비어있어도 블록에 대한 응답은 받을 수 있다.
=> [BSVR-162] 블록별 리뷰 조회 Location 정보 최상단으로 응답 구조 변경

application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java, common/src/main/java/org/depromeet/spot/common/exception/member/MemberErrorCode.java, common/src/main/java/org/depromeet/spot/common/exception/member/MemberException.java, domain/src/main/java/org/depromeet/spot/domain/member/Member.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberJpaRepository.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/MemberRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
- 회원 탈퇴 soft delete 구현
<br>
- 회원 탈퇴 soft delete API 추가
- 회원 탈퇴 유저 로그인 시 재가입 처리
- 
<br>
- 성공
- 삭제 후 로그인 (재가입 처리)
=> [BSVR-152] 회원 탈퇴 soft delete API

application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java, application/src/main/java/org/depromeet/spot/application/review/dto/request/CreateReviewRequest.java, common/src/main/java/org/depromeet/spot/common/exception/review/ReviewErrorCode.java, common/src/main/java/org/depromeet/spot/common/exception/review/ReviewException.java
- 리뷰 생성 API에서 request 필드들에 대한 제약 조건을 업데이트했어요.
<br>
**`기존`**
- @NotNull List<String> good, @NotNull List<String> bad
**`변경`**
- @NotNull 어노테이션 삭제 및 키워드가 둘 다 비어있으면 RV004 custom exception(아래 사진에 나와있음)을 반환하는 validateGoodAndBad 메서드 구현 및 적용
**`기존`**
- yy.mm.dd
**`변경`**
- yyyy-mm-dd HH:mm
**`기존`**
- @NotNull String content
**`변경`**
- String content
<br>
- keyword가 하나만 들어와도 잘 저장되고, 조회도 잘된다.
- keyword가 둘 다 비어있는 째로 들어온다면 아래와 같이 custom exception을 반환한다.
=> [BSVR-169] 리뷰 생성 API req validation 업데이트: 키워드 개수 조건, 날짜 포맷

application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
- GUI 업데이트 되면서 추가된 리뷰 pk로 특정 리뷰를 조회해오는 api를 구현했어요. 
- [API 명세서](https://www.notion.so/depromeet/NEW-018781796c6345af8de5205becd0c3ee?pvs=4)
<br>
- 이미 repository에 findById 함수가 구현이 되어있어서 service 함수와 controller만 만들어줬어요.
- 서비스 함수에서 리뷰객체와 키워드 객체를 매핑하는 코드가 많이 겹쳐서 리팩토링을 수행했어요.
<br>
- 잘된다!, service에서 리뷰 객체와 키워드 객체를 매핑하는 함수를 리팩토링해서 다른 조회 API도 postman에서 잘 작동하는 것을 확인!
=> [BSVR-173] 리뷰 pk로 특정 리뷰 조회 API 구현

application/src/main/java/org/depromeet/spot/application/stadium/dto/response/HomeTeamInfoResponse.java, domain/src/main/java/org/depromeet/spot/domain/team/BaseballTeam.java, domain/src/test/java/org/depromeet/spot/domain/team/BaseballTeamTest.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/entity/BaseballTeamEntity.java, infrastructure/jpa/src/main/resources/application-jpa.yaml, infrastructure/jpa/src/main/resources/data.sql, usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/ReadStadiumHomeTeamUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/team/ReadStadiumHomeTeamService.java
- 구장별 홈 팀 label 폰트 색상을 서버에서 관리해요.
- ref) [관련 스레드](https://depromeet-15th.slack.com/archives/C076JJKKR4H/p1722143725606359)
<br>
- BaseballTeam Entity에 폰트 필드 추가
- BaseballTeam 도메인에 폰트 필드 추가
- 관련 테스트코드 수정
- 홈 팀 조회 API들에 res에 폰트 추가
- data.sql 수정
<br>
- dev DB에 테이블 alter 날린 후 배포 예정!
<br>
- 기존에 있던 홈 팀 관련 API res만 슥 수정했어용
전체 경기장 조회 API
특정 경기장 조회 API
=> [BSVR-168] 홈 팀 label 폰트 색상 추가

application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java, application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java
- #96 이후 리뷰 작성 API의 res에 유저 레벨이 변경되지 않은 채로 반환되는 이슈 발견
- 원인 : 유스케이스에선 레벨이 업데이트 된 유저 도메인을 반환하는데, 정작 컨트롤러에서 response dto 매핑해줄 때 레벨 업데이트 되기 전의 유저 도메인을 사용하고 있었음
<br>
- 리뷰 작성 API res dto 변환 로직 수정
=> [NO_JIRA] 리뷰 작성 API res에 레벨 업데이트 전 멤버 정보가 반환되는 버그

application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
- 내 리뷰 조회 API res 수정 : 팀이름, 팀 id 포함
<br>
- ReadReviewService에서 member의 teamId를 통해 BaseballTeam에서 팀의 이름을 가지고 와서 리뷰를 반환할 때 유저 정보에 pk와 함께 팀 이름을 반환
<br>
- memberInfoOnMyReview에 teamId와 teamName이 추가되어 아주 잘 반환된다!
=> [BSVR-184] 내 리뷰 조회 API res 수정 : 팀이름, 팀 id 포함

application/src/main/java/org/depromeet/spot/application/member/dto/request/RegisterReq.java, infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/member/UpdateMemberService.java
- 응원하는 팀이 없는 (= 모든 팀 응원) 유저가 존재해요.
- 따라서 Member.teamId를 nullable하게 수정해요.
- [관련 스레드](https://depromeet-15th.slack.com/archives/C075Z9K5QH4/p1722595109574709)
<br>
- MemberEntity에서 teamId nullable으로 변경
- 응원 구단이 nullable하게 바뀐것에 영향받는 코드 수정
- members 테이블 team_id를 nullable로 alter (PR merge될 때 개발 DB에 반영 예정)
<br>
- 멤버 부분은 내가 작업했던 코드가 아니라, 혹시 수정 누락된 부분이 있는지 담당자 확인이 필요해요 @wjdwnsdnjs13 
<br>
프로필 수정할 때 team null로 넣어도 잘 동작!
=> [NO_JIRA] Member 응원 팀을 nullable로 변경

application/build.gradle.kts, application/src/main/java/org/depromeet/spot/application/common/config/SecurityConfig.java, application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java, application/src/main/resources/appenders/console-appender.xml, application/src/main/resources/application.yaml, application/src/main/resources/logback-spring.xml, versions.properties
- 서버 모니터링 파이프라인 구축을 위해, 스프링에서 필요한 설정을 추가해요.
<br>
- spring actuator, prometheus, loki 의존성 추가
- actuator, prometheus endpoint 활성화 및 인증 필터에서 제외
- loki appender 생성 및 prod에 적용
<br>
- 기본 spring 포트인 8080을 그대로 쓰면 외부에서 actuator metric에 접근 가능할 것 같아서, 내부만 접근 가능하도록 9292 포트를 열었어요. ec2 설정할 때 참고!
- 주석으로 남겨놨는데, 나중에 loki 인스턴스가 세팅되면 loki appender의 url을 인스턴스 주소로 바꿔줘야 해요.
<br>
- actuator 리스트
- prometheus 메트릭 활성화 확인
=> [BSVR-185] spring actuator, prometheus, loki 의존성 및 설정

usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
- 홈 피드 API teamId null 시 발생하는 오류 수정
```
{
"level": 6,
"teamName": null,
"teamId": null,
"levelTitle": "전설의 직관러",
"reviewCntToLevelUp": null,
"mascotImageUrl": null
}
```
<br>
- MemberInfo 변환 시 build 누락 휴먼 에러 수정
- teamId null 시 리턴 이후 리뷰 카운트 로직이 들어있던 부분 수정
<br>
- 수정 완료!
=> [NO_JIRA] 홈 피드 API teamId null 시 발생하는 오류 수정

usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
- reviews API teamId == null 오류 fix
<br>
- reviews API teamId == null 일 때 분기 처리
- MemberInfoOnMyReviewResult 변환 메서드 해당 클래스 멤버 메서드로 리팩토링
<br>
- teamId == null 일 때 성공!
=> [NO_JIRA] reviews teamId null 일 때 오류 fix

application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java, application/src/main/java/org/depromeet/spot/application/member/controller/ReadLevelController.java, application/src/main/java/org/depromeet/spot/application/member/dto/response/LevelUpDialogInfo.java, domain/src/main/java/org/depromeet/spot/domain/member/Level.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/entity/LevelEntity.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/repository/LevelJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/repository/LevelRepositoryImpl.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/LevelUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/level/LevelService.java
- 레벨업 다이얼로그 GUI가 추가되었어요.
- [관련 스레드](https://depromeet-15th.slack.com/archives/C075Z9K5QH4/p1722706109884659)
<br>
- 레벨 도메인, 레벨 엔티티에 레벨업 이미지 필드 추가
- 레벨업 정보 조회 API 추가
- 유저의 리뷰 수 조회할 때 삭제된 리뷰도 count하는 이슈 수정
<br>
- PR merge 전 DB alter 예정
<br>
=> [BSVR-188] Level up 다이얼로그용 API

usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/DeleteReviewService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
- resolve #112 
<br>
- 리뷰를 삭제한 후, 멤버 레벨을 재조정해요.
<br>
- 로컬에서 리뷰 삭제 후, 레벨 떨어지는 것 확인완료
=> [NO_JIRA] 리뷰 삭제시 멤버 레벨 재조정

application/src/main/java/org/depromeet/spot/application/common/config/SpotApplicationConfig.java, infrastructure/build.gradle.kts, infrastructure/src/main/java/org/depromeet/spot/infrastructure/cache/CacheType.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/cache/config/CacheConfig.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/seat/repository/SeatJpaRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/block/BlockReadService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/level/LevelService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/seat/ReadSeatService.java, versions.properties
- caffeine 캐시를 추가하고, 몇몇 데이터에 캐시를 적용해요.
- resolve #88 
<br>
- 스프링 캐시, 카페인 캐시 설정 추가
- 구역별 좌석 정보, 블럭별 좌석 정보, 레벨 정보 캐시 추가
<br>
- 배포 후 
- 메모리 사용량 보면서 조정 필요
- 잘 변하지 않으면서 자주 조회되는 값이라 캐시를 적용하긴 했는데, 적용 이전에도 5-600ms라서 엄청 느리진 않아요.
- 메모리 점유율이 높고, 인스턴스 스펙이 부족하다면, 그때 캐시 조정 여부 논의하면 될 듯!
- time-based evice 잘 되는지 모니터링 필요
=> [BSVR-166] 로컬 캐시 적용

application/src/main/resources/appenders/console-appender.xml, application/src/main/resources/logback-spring.xml
- Loki 오류 fix
<br>
- loki appender 수정
- 기존 appender 태그를 바로 쓴 방식이 문제가 있었던 것 같음. ([공식 문서](https://loki4j.github.io/loki-logback-appender/)에서도 configuration 하위에 appender 태그로 설정해준 후 appender-ref 태그로 사용하고 있었음.)
- 문제 해결 후 console-append.xml 파일로 loki appender 설정 옮김
- 기존에 안됐던 이유가 서버 인스턴스 3100번 포트가 막혀있어서 동작하지 않았던 것으로 예상하는 중...!
- #133 
<br>
- 모니터링 인스턴스의 로키에서 정상적으로 로깅 완료
=> [NO_JIRA] loki 오류 fix

application/src/main/resources/logback-spring.xml
- spring active profile이 local 일때는 Loki appender를 적용하지 않아요.
<br>
- logback 수정
=> [NO_JIRA] local profile에서 loki 비활성화

usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java
- 기존 코드에서 키워드, 이미지 관련 작업을 묶어서 처리하게 리팩토링했더니 이슈 발생
- 리뷰는 정상적으로 등록되는데, 키워드/이미지가 등록되지 않음
- 리팩토링 과정에서 메서드 순서를 바꾼 것이 원인으로 확인 -> 원복
<br>
- 어드민 리뷰 등록 과정에서 이미지, 키워드 처리 로직의 순서 변경
<br>
- 로컬 실행 화면
=> [NO_JIRA] 어드민 리뷰 등록시 키워드, 이미지 등록 로직 순서 변경

application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java, application/src/main/java/org/depromeet/spot/application/review/dto/response/BlockReviewListResponse.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/ReviewEntity.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewCustomRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java, infrastructure/src/main/resources/application-jpa.yaml
- 리뷰에서 좌석 번호가 선택값으로 바뀜에 따라, 리뷰 조회 API에서 seat를 nullable 하게 바꿔요.
<br>
- 리뷰 조회 관련 API res에서 seat nullable하게 수정
- (성능 개선) 블록별 리뷰 조회 메서드에서 리뷰 조회할 때 N+1 발생하는 것 수정
<br>
- AOS 작업 완료 후 merge & 배포 예정
- 리뷰 조회 부분이 원래 제 담당이 아니라.. 로컬에서 동작하는걸 확인하긴 했지만, 좀 불안하네요ㅋㅋㅠ
- 실제로 블록별 리뷰 조회는 seat_id = null 인 경우는 기존 쿼리가 처리해주지 못해서 쿼리를 수정했어요!
- 혹시 논리 오류가 발생하진 않는지 한 번씩 크로스체크 해주면 좋을 것 같아요! @pminsung12 @wjdwnsdnjs13 
<br>
- 특정 리뷰 조회 API
- 내가 쓴 리뷰 조회 API
- 내가 마지막으로 쓴 리뷰 조회 API
- 블록별 리뷰 조회 API (seat == null인 경우 / null 아닌 경우 각각 테스트 완료)
=> [BSVR-213] 리뷰 조회 API에 seat nullable 반영 & 기존 메서드의 N+1 수정

.github/workflows/dev-build-and-deploy.yaml, .github/workflows/manual-prod-deploy.yaml, application/src/main/java/org/depromeet/spot/application/common/config/SpotApplicationConfig.java, infrastructure/build.gradle.kts, infrastructure/src/main/java/org/depromeet/spot/infrastructure/InfrastructureConfig.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/RedisConfig.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/RedisProperties.java, versions.properties
- #132 연관 작업
- spring-redis 세팅
<br>
- (gitignore) application-aws에 redis 추가 
- redis 설정파일 추가
- (리팩토링) InfrastructureConfig 생성 (JpaConfig, CacheConfig, AWSConfig 등 포함)
- dev, prod 배포를 위해 redis 환경변수를 추가했어요.
- [컨플루언스](https://dpm-15th-6team.atlassian.net/wiki/spaces/SPOT/pages/1409025#ElastiCache-Redis-(ssh-tunneling-%ED%95%84%EC%9A%94))에 스펙 있음! 
<br>
- ElastiCache에 터널링해서 접근해야 해요.
- 로컬에서는 다음 방법 중 하나를 택해서 진행하면 됩니다.
- (권장) 로컬에 redis 설치 후, application-aws에 localhost 넣고 쓰기
- 로컬에서 ssh 터널링 한 후, application-aws에 dev 서버 host 넣고 쓰기
- dev까진 괜찮은데, **로컬에서 prod에 직접 붙는건 XXXXXX 절대 금지! 주의해주세용**
- application-aws.yml 필요
- [컨플루언스](https://dpm-15th-6team.atlassian.net/wiki/spaces/SPOT/pages/4882433/application-aws.yaml)에 추가 완료!
=> [BSVR-212] AWS ElastiCache Redis 세팅

application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java, application/src/main/java/org/depromeet/spot/application/review/dto/response/BlockReviewListResponse.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewCustomRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
- 리뷰에서 seat nullable하게 수정 2 + totalElements 필드 추가
<br>
- BaseReviewResponse에서 빠진 seat nullable 처리
- block 리뷰 조회에서 요구사항에 따라 total elements 필드 추가
- [관련 스레드](https://depromeet-15th.slack.com/archives/C075Z9K5QH4/p1724050120911709?thread_ts=1723474743.177719&cid=C075Z9K5QH4)
<br>
- 커서 기반으로 해서 전체를 다 훑을 필요없이 정렬 후 size 만큼만 가져오는 최적화를 수행했었는데,, 
- 아이러니하게도 요구사항 상 전체 개수가 필요해서 어쩔 수 없이 필터 조건에 따라 항상 전체 element 수를 가져와야하기 때문에 풀스캔을 때려야한다... 최적화 방법이 있을까? 
<br>
=> [BSVR-224] 리뷰에서 seat nullable하게 수정 2 + totalElements 필드 추가

application/src/main/java/org/depromeet/spot/application/section/dto/request/CreateSectionRequest.java, application/src/main/java/org/depromeet/spot/application/section/dto/response/SectionInfoResponse.java, application/src/main/java/org/depromeet/spot/application/stadium/dto/response/HomeTeamInfoResponse.java, application/src/main/java/org/depromeet/spot/application/team/CreateBaseballTeamController.java, domain/src/main/java/org/depromeet/spot/domain/section/Section.java, domain/src/main/java/org/depromeet/spot/domain/team/BaseballTeam.java, domain/src/test/java/org/depromeet/spot/domain/team/BaseballTeamTest.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/section/entity/SectionEntity.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/section/repository/SectionJdbcRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/team/entity/BaseballTeamEntity.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/team/repository/BaseballTeamJdbcRepository.java, infrastructure/src/main/resources/data.sql, usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/CreateSectionUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/SectionReadUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/CreateBaseballTeamUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/ReadStadiumHomeTeamUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/team/CreateBaseballTeamService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/team/ReadStadiumHomeTeamService.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeBaseballTeamRepository.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSectionRepository.java, usecase/src/test/java/org/depromeet/spot/usecase/service/section/SectionReadServiceTest.java, usecase/src/test/java/org/depromeet/spot/usecase/service/team/CreateBaseballTeamServiceTest.java, usecase/src/test/java/org/depromeet/spot/usecase/service/team/ReadBaseballTeamServiceTest.java
- GUI 변경으로 구역 label, 홈팀 label 색상에 그라디언트 요소가 추가되었어요.
- 따라서 색상 관련 값을 AOS에서 관리하게 되었으므로, 관련 필드와 코드를 수정 & 삭제해요.
- 폰트 색상은 단색이라 서버에서 관리하는 것 유지!
<br>
- section의 labelColor 삭제
- baseballTeam의 labelBackgroundColor 삭제
- 관련 테스트코드 수정
- 관련 usecase 코드 수정
- 관련 request, response 코드 수정
- data.sql 수정
<br>
- AOS가 서버가 내려주는 색상 필드를 사용하는 코드를 수정하기 전까지는 merge되면 안되는 PR이에요.
- 리뷰만 미리 해주세요! 이후 AOS에게 핑 받으면 merge & DB table alter한 후 배포할게요~
<br>
> 로컬에서 table alter 후 실행했어요~
- 구역 조회 API
- 구역 생성 API
- 홈 팀 조회 관련 API들
- 구단 생성 API (multipart 필요해서 swagger로..)
=> [BSVR-199] section, baseballTeam의 label color 삭제

domain/src/main/java/org/depromeet/spot/domain/block/BlockTag.java, domain/src/main/java/org/depromeet/spot/domain/hashtag/HashTag.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/entity/BlockTagEntity.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/tag/BlockTagJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/common/entity/BaseEntity.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/hashtag/HashTagEntity.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/hashtag/entity/HashTagEntity.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/hashtag/repository/HashTagJpaRepository.java, infrastructure/src/test/java/org/depromeet/spot/infrastructure/jpa/hashtag/HashTagEntityTest.java
- 경기장별 블록 필터링 기능을 위해 해시태그 관련 도메인/엔티티를 추가해요.
- 한 블록은 여러 태그를 가질 수 있고, 태그에는 여러 블록이 포함될 수 있어요. (= 다대다)
<br>
- HashTag, BlockTag 도메인 추가
- HashTagEntity, BlockTagEntity 추가
- 관련 테스트코드 추가
- jpaRepository 추가
<br>
- DB에 테이블은 미리 생성해뒀어요. [ref)](https://depromeet-15th.slack.com/archives/C075Z9K5QH4/p1723985648038789)
<br>
local에서 hibernate.ddl-auto=validate로 했을 때 잘 돌아감~
=> [BSVR-220] HashTag, BlockTag 도메인/엔티티 추가

application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumBlockTagResponse.java, application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumInfoWithSeatChartResponse.java, application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumSectionInfoResponse.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/entity/BlockTagEntity.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/tag/BlockTagCustomRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/tag/BlockTagJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/tag/BlockTagRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/ReadBlockTagUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/SectionReadUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/stadium/StadiumReadUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockTagRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/block/ReadBlockTagService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/section/SectionReadService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
- 2차 MVP GUI 변경 -> 구역 일괄 선택 기능, 블록 필터링 기능이 추가되었어요.
- 위 변경에 맞춰 필요한 res를 추가해요.
<br>
- 해시태그에 description 필드 추가
- 경기장별 구역 정보값 추가
- 경기장별 블럭 해시태그 정보값 추가
<br>
추가된 필드 부분만 캡처했어요~
=> [BSVR-221] 특정 경기장 상세 정보 조회 API에 구역 정보, 블록 해시태그 정보 추가

infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/image/ReviewImageEntity.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewImageProcessor.java
메서드 이름만! 보지 말고! 주석을! 읽자! 
삼세번 복창하겠읍니다 죄송합니다 😩
=> [NO_JIRA] 이미지 파일 이름 받아오는 코드 수정

application/src/main/java/org/depromeet/spot/application/review/scrap/ReviewScrapController.java, domain/src/main/java/org/depromeet/spot/domain/review/scrap/ReviewScrap.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/scrap/ReviewScrapEntity.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/scrap/ReviewScrapUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewScrapRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/scrap/ReviewScrapService.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeReviewScrapRepository.java, usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewScrapServiceTest.java
- https://www.notion.so/depromeet/or-ea77aa315bdb43ee8954c23a9252be17?pvs=4
- 특정 리뷰의 스크랩을 추가하고 제거하는 api를 구현했어요.
- 공감과 마찬가지로 서버에서 스크랩 여부를 확인해서 api 하나로 스크랩 추가와 제거를 통일했어요.
<br>
- controller, service, repository 구현
- 테스트코드 구현
<br>
- X
<br>
- review scrap 테이블 추가
```mysql
CREATE TABLE `review_scraps` (
`id` bigint NOT NULL AUTO_INCREMENT,
`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
`updated_at` datetime DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
`deleted_at` datetime DEFAULT NULL,
`member_id` bigint NOT NULL ,
`review_id` bigint NOT NULL ,
PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
<br>
- 테스트 통과
- 추가할 땐 true 반환, 제거할 땐 false 반환
- review scrap 테이블 추가
=> [BSVR-227] 스크랩 토글 API 구현

application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java, application/src/main/java/org/depromeet/spot/application/review/scrap/ReviewScrapController.java, domain/src/main/java/org/depromeet/spot/domain/review/Review.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/ReviewEntity.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/UpdateReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/UpdateReviewService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/scrap/ReviewScrapService.java, usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewScrapServiceTest.java
- 스크랩 개수 저장 로직 추가
<br>
<br>
<br>
- @EunjiShin  갓 은 지의 공감 파트 로직이 똑같아 코드를 참고함. (베낌)
- dev와 prod 테이블에 아래의 sql문 적용해서 review 테이블에 scraps_count 컬럼 추가
```sql
alter table reviews add column scraps_count int DEFAULT 0;
```
<br>
=> [BSVR-231] 스크랩 개수 저장 로직 추가

application/src/main/java/org/depromeet/spot/application/review/dto/request/PageRequest.java, application/src/main/java/org/depromeet/spot/application/review/dto/request/scrap/MyScrapRequest.java, application/src/main/java/org/depromeet/spot/application/review/dto/response/MyReviewListResponse.java, application/src/main/java/org/depromeet/spot/application/review/dto/response/scrap/MyScrapListResponse.java, application/src/main/java/org/depromeet/spot/application/review/scrap/ReviewScrapController.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapCustomRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/page/PageCommand.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/scrap/ReviewScrapUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewScrapRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/scrap/ReviewScrapService.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeReviewScrapRepository.java, usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewScrapServiceTest.java
- 스크랩한 리뷰 내려주는 api 구현
<br>
<br>
<br>
<br>
=> [BSVR-228] 스크랩한 리뷰 내려주는 api 구현

application/src/main/java/org/depromeet/spot/application/review/dto/request/CreateReviewRequest.java, application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java, domain/src/main/java/org/depromeet/spot/domain/review/Review.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/ReviewEntity.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/CreateReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewCreationProcessorImpl.java
- 등록 플로우 시야 후기, 직관 후기 분리 
- https://www.notion.so/depromeet/9df0ab254a9c4d8497c9e8b26f83de58?pvs=4
<br>
- 직관 후기와 시야 후기는 등록, 조회 플로우가 완전히 같기 떄문에(다른 건 사진 뿐) 등록 api를 통일했어요.
- request body에 reveiwType 컬럼을 추가해서 `VIEW`면 시야후기, `FEED`면 직관 후기로 리뷰 테이블에 등록하도록 했어요.
- body에 reviewType이 들어오지 않으면 디폴트로 'VIEW'로 저장되도록 했어요.
- 리뷰 응답 필드에도 reviewType 필드를 추가했어요.
<br>
- x
<br>
- dev, prod에 review_type 컬럼 추가
```sql
ALTER TABLE reviews ADD COLUMN review_type VARCHAR(15) NOT NULL DEFAULT 'VIEW';
```
<br>
=> [BSVR-229] 등록 플로우 시야 후기, 직관 후기 분리 

application/src/main/java/org/depromeet/spot/application/review/dto/response/BlockReviewListResponse.java, application/src/main/java/org/depromeet/spot/application/review/dto/response/MyReviewListResponse.java, domain/src/main/java/org/depromeet/spot/domain/review/Review.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewCustomRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/image/ReviewImageCustomRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/image/ReviewImageJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/image/ReviewImageRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewImageRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
- 블록 리뷰 조회 시야 후기 조회 
- top review image 정책 업데이트
- [2차 MVP 블록별 리뷰 조회 API 슬랙 논의](https://depromeet-15th.slack.com/archives/C075Z9K5QH4/p1724330990864519)
<br>
- 블록 리뷰 조회할 때 likesCount랑 scrapsCount 컬럼 포함하도록 업데이트
- 블록 리뷰 조회할 때 시야후기만 조회하도록 업데이트(직관후기는 비공개)
- top review images에 리뷰 전체 정보를 포함할 수 있도록 업데이트
- top review images 정책 변경 반영: 최신순 -> 공감순 - 최신순
<br>
- x
<br>
- x
<br>
=> [BSVR-230] 블록 리뷰 조회 시야 후기 조회 + top review image 정책 업데이트

application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java, application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java, domain/src/main/java/org/depromeet/spot/domain/review/Review.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/like/ReviewLikeJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/like/ReviewLikeRepositoryImpl.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewLikeRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewScrapRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeReviewScrapRepository.java
- 블록 리뷰에 유저가 좋아요, 스크랩을 눌렀는 지 안 눌렀는지 확인 필드 추가
<br>
- [리뷰 도메인과 response에 isScrapped, isLiked 필드 추가](https://github.com/depromeet/SPOT-server/commit/622c4e14aa5c9d402347e8be6fd1f1552abebe59)
- [memberId로 조회해 온 리뷰들의 좋아요/스크랩 여부 업데이트하는 서비스 로직 구현](https://github.com/depromeet/SPOT-server/commit/a073baa098137e751d8fc25c2f3595ed01dfa7e4)
- [유저별 리뷰들 좋아요, 스크랩 여부 조회해오는 레포지토리 메서드 구현](https://github.com/depromeet/SPOT-server/commit/01af3463fe7e4611629fe225feee016abf7e927e)
<br>
- x
<br>
- x
<br>
=> [BSVR-241] 블록 리뷰에 유저가 좋아요, 스크랩을 눌렀는 지 안 눌렀는지 확인 필드 추가

application/src/main/java/org/depromeet/spot/application/review/scrap/ReviewScrapController.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReadReviewProcessor.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReadReviewProcessorImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/scrap/ReviewScrapService.java, usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewScrapServiceTest.java
- 스크랩 조회 get요청에 request body쓴 이슈  + scrapsCount 조회 안되는 이슈 픽스
<br>
- [스크랩 조회 시 get요청에 request body를 사용한 것을 param으로 수정](https://github.com/depromeet/SPOT-server/commit/59b556e4738e92c06cf67030471377e1b08fdded)
- [keyword 매핑부분에서 scrapsCount 빌더에 추가](https://github.com/depromeet/SPOT-server/commit/b69911ae0d872eba54907e6f58abae32458ab774)
- [스크랩 조회 시 isScrapped, isLiked 업데이트 로직 추가](https://github.com/depromeet/SPOT-server/commit/04917d08760aec08323357a284f23fc5b8e0c19f)
- 스크랩 조회 시 사용자의 스크랩, 좋아요 여부 업데이트 추가
<br>
- x
<br>
- x
<br>
=> [BSVR-242] 스크랩 조회 get요청에 request body쓴 이슈  + scrapsCount 조회 안되는 이슈 픽스

application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java, application/src/main/java/org/depromeet/spot/application/review/dto/request/MyReviewRequest.java, application/src/main/java/org/depromeet/spot/application/review/dto/response/MemberInfoOnMyReviewResponse.java, application/src/main/java/org/depromeet/spot/application/review/dto/response/MyReviewListResponse.java, domain/src/main/java/org/depromeet/spot/domain/review/ReviewCount.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewCustomRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
- 시야 아카이빙 시야 후기/직관 후기 분리
- https://depromeet-15th.slack.com/archives/C075Z9K5QH4/p1724327340969699
<br>
- [내 리뷰 조회 repository를 review type에 따라 조회하도록 업데이트](https://github.com/depromeet/SPOT-server/commit/64f2e3efe28e7aaa607381836c2503d0a26af451)
- [내 리뷰 조회 reviewType 디폴트를 VIEW로 설정](https://github.com/depromeet/SPOT-server/commit/d9b3124a7f26d255142bc12d89caf481f6a06a80)
- [유저별 리뷰 총 개수와 좋아요 합계를 가지는 ReviewCount 도메인 구현](https://github.com/depromeet/SPOT-server/commit/d526c8e6b6133320bafbe28ba6877569c93cb32d)
- [내 리뷰 조회에서 유저 정보 API 분리](https://github.com/depromeet/SPOT-server/commit/46811e825745b9334861279d51c3f15f9ed6ee01)
- [review type 관련한 쿼리문 버그 픽스](https://github.com/depromeet/SPOT-server/commit/c8e72b7e63c9faff9dac9a22971b1201bfea6692)
<br>
- x
<br>
- x
<br>
- 시야 아카이빙 유저 정보 조회
- 시야 아카이빙 …
=> [BSVR-234] 시야 아카이빙 시야 후기/직관 후기 분리

application/src/main/resources/application.yaml, infrastructure/build.gradle.kts, infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/EmbeddedRedisConfig.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/RedissonConfig.java, versions.properties
- 현재 aws ElastiCache (redis)를 사용 중이에요.
- 그런데 로컬이나 테스트 profile에서 dev / prod redis를 사용하면 데이터가 꼬일 수 있어요.
- 캐시 목적으로 사용하면 캐시 데이터가 겹칠 수 있고
- 분산락 목적으로 사용하면 락 획득을 위한 대기 시간이 길어질 수도 있고... 
- redis를 로컬에서 직접 설치해서 사용해도 되지만, 최대한 프로젝트를 clone받고 바로 실행해볼 수 있는 상황으로 만들고 싶었어요.
- 따라서 local & test profile에서는 [embedded redis opensource](https://github.com/ozimov/embedded-redis)를 활용하도록 설정해요.
<br>
- embedded redis 설정 추가
<br>
- 각자 local에서 pull 받고 잘 동작하는지 한 번씩 체크해주세요~
<br>
- 이미 레디스 포트(6379)를 사용 중이라 다른 포트를 배정한 경우
=> [BSVR-239] 로컬/테스트에서 redis를 사용하기 위한 세팅

usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewCreationProcessorImpl.java
- https://depromeet-15th.slack.com/archives/C075Z9K5QH4/p1724584613683069
- 어드민 리뷰 생성에서 ReviewType 때문에 insert에서 버그 발생
<br>
- `ReviewCreationProcessor`에서 insert하기 전 build하는 리뷰에 디폴트 값 `ReviewType.VIEW`로 `reviewType` 필드 추가
<br>
- x
<br>
- x
<br>
=> [BSVR-250] 어드민 리뷰 생성에서 ReviewType 때문에 insert에서 버그 발생

.github/workflows/dev-build-and-deploy.yaml, .github/workflows/manual-prod-deploy.yaml, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/entity/GoogleUserInfoEntity.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/entity/KakaoUserInfoEntity.java
- 기본 프로필 이미지 변경
<br>
- 기본 프로필 이미지 변경
- 기본 프로필 이미지 환경 변수 추가
- [컨플루언스](https://dpm-15th-6team.atlassian.net/wiki/spaces/SPOT/pages/4882433/application-aws.yaml) 참고해서 application-aws에 환경 변수 추가해주세요 :)
<br>
설정해둔 기본 프로필이 들어가는 것까지 확인 완료!
=> [NO_JIRA] 기본 프로필 이미지 변경

.github/workflows/dev-build-and-deploy.yaml, .github/workflows/manual-prod-deploy.yaml
<br>
- Spring Boot의 기본 멀티파트 설정
- 최대 파일 크기 (max-file-size): 기본값: 1MB
- 최대 요청 크기 (max-request-size):기본값: 10MB
=> 둘 다 30MB로 직접 지정
<br>
- x
<br>
- x
<br>
=> [BSVR-252] 어드민 리뷰 등록 Multipart 오류

application/src/main/java/org/depromeet/spot/application/review/dto/request/UpdateReviewRequest.java, application/src/main/resources/application.yaml, domain/src/main/java/org/depromeet/spot/domain/review/ReviewLocationInfo.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/row/BlockRowJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/row/BlockRowRepositoryImpl.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/seat/repository/SeatRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/UpdateReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockRowRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/seat/SeatRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/UpdateReviewService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewCreationProcessor.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewCreationProcessorImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewDataProcessor.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewDataProcessorImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewKeywordProcessor.java, usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSeatRepository.java
- 리뷰 수정 API 업데이트 - 요청 필드 추가, nullable 처리
- 관련 논의 >> [slack](https://depromeet-15th.slack.com/archives/C075Z9K5QH4/p1725721464779689)
<br>
- request 필드에 stadiumId, rowNumber, reviewType 추가
- 최대한 적게 디스크에 접근하기 위해 케이스 꼼꼼하게 처리
- 세부로직은 processor로 이관하여 리팩토링 진행
<br>
- 다음 pr에 이부분 최적화 진행할 예정 - for문 돌면서 계속 디스크에 접근하는 구조라 비효율적임.
```java
public Map<Long, Keyword> processKeywords(
Review review, List<String> goodKeywords, List<String> badKeywords) {
Map<Long, Keyword> keywordMap = new HashMap<>();
processKeywordList(review, goodKeywords, true, keywordMap);
processKeywordList(review, badKeywords, false, keywordMap);
return keywordMap;
}
// FIXME: 쿼리 호출 부분 개선 필요
private void processKeywordList(
Review review,
List<String> keywordContents,
boolean isPositive,
Map<Long, Keyword> keywordMap) {
for (String …
```
=> [BSVR-257] 리뷰 수정 API 업데이트 - 요청 필드 추가, nullable 처리

usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/UpdateReviewService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReadReviewProcessor.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReadReviewProcessorImpl.java
- 리뷰 수정 isLiked, isScrapped 버그 해결
<br>
-  [ReadReveiwProcessor에 isLiked, isScrapped 조회 메서드 구현](https://github.com/depromeet/SPOT-server/commit/cb2933d5b2deea8a91e131bf7435c6482a8c687e)
- [업데이트 시 isLiked, isScrapped 상태 조회](https://github.com/depromeet/SPOT-server/commit/a93839ef857ee20bfcf242bbd6cdaa08fa02d5e2)
<br>
=> [BSVR-260] 리뷰 수정 isLiked, isScrapped 버그 해결

application/src/main/java/org/depromeet/spot/application/member/controller/JwtCreateController.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewJpaRepository.java, infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java, usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/DeleteReviewUsecase.java, usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java, usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java, usecase/src/main/java/org/depromeet/spot/usecase/service/review/DeleteReviewService.java
- 탈퇴 시 리뷰 삭제 구현
- Prod에서 jwt 토큰 생성 API 비활성화
<br>
- 탈퇴 시 리뷰 삭제 구현
- Prod에서 jwt 토큰 생성 API 비활성화
- jwt 토큰 생성 API가 권한이 필요하거나 한 게 아니라서 Prod에서는 사용할 수 없게 비활성화 함!
<br>
- 탈퇴했을 때 정보 삭제하는 것들도 이벤트나 큐로 처리하는 게 좋을까 고민 중...
<br>
- 탈퇴하면, 리뷰도 정상 삭제 완료 확인!
=> [BSVR-254] 탈퇴 시 리뷰 삭제 구현
